const IMAGES = {
    profile: require("../assets/images/profile.jpg"),
    fast_food_item: require('../assets/images/fast_food_item.png'),
    fruits_item: require('../assets/images/fruit_item.png'),
    rice_item: require('../assets/images/rice_item.png'),
    fast_food1: require('../assets/images/fast_food1.png'),
    fast_food2: require('../assets/images/fast_food2.png'),
    fast_food3: require('../assets/images/fast_food3.png'),
    fast_food4: require('../assets/images/fast_food4.png'),
    fast_food5: require('../assets/images/fast_food5.png'),
    fast_food6: require('../assets/images/fast_food6.png'),
    fruit_item1: require('../assets/images/fruit_item1.png'),
    fruit_item2: require('../assets/images/fruit_item2.png'),
    fruit_item3: require('../assets/images/fruit_item3.png'),
    fruit_item4: require('../assets/images/fruit_item4.png'),
    fruit_item5: require('../assets/images/fruit_item5.png'),
    fruit_item6: require('../assets/images/fruit_item6.png'),
    rice_item1: require('../assets/images/rice_item1.png'),
    rice_item2: require('../assets/images/rice_item2.png'),
    rice_item3: require('../assets/images/rice_item3.png'),
    rice_item4: require('../assets/images/rice_item4.png'),
    rice_item5: require('../assets/images/rice_item5.png'),
    rice_item6: require('../assets/images/rice_item6.png'),
}

export default IMAGES
